import { ExpansionURN } from '../domain/expansion.urn.js';
import { GameURN } from '../domain/game.urn.js';
import type { Game } from './game.model.js';

/** In-memory catalogue. No persistence, per the demo's scope. */
export const GAMES_CATALOGUE: readonly Game[] = [
  {
    urn: GameURN.stringify('wingspan'),
    title: 'Wingspan',
    mechanisms: ['engine building', 'set collection'],
    players: '1-5',
    playtime: '40-70 min',
    complexity: 2.4,
    price: 59900,
    availability: 'in-stock',
    expansions: [
      {
        urn: ExpansionURN.forGame('wingspan', 'europe'),
        title: 'European Expansion',
        price: 29900,
      },
      {
        urn: ExpansionURN.forGame('wingspan', 'oceania'),
        title: 'Oceania Expansion',
        price: 32900,
      },
    ],
  },
  {
    urn: GameURN.stringify('brass-birmingham'),
    title: 'Brass: Birmingham',
    mechanisms: ['economic', 'network building'],
    players: '2-4',
    playtime: '60-120 min',
    complexity: 3.9,
    price: 74900,
    availability: 'reprint-pending',
    expansions: [],
  },
  {
    urn: GameURN.stringify('gloomhaven'),
    title: 'Gloomhaven',
    mechanisms: ['co-op', 'legacy', 'tactical combat'],
    players: '1-4',
    playtime: '60-120 min',
    complexity: 3.9,
    price: 149900,
    availability: 'in-stock',
    expansions: [
      {
        urn: ExpansionURN.forGame('gloomhaven', 'forgotten-circles'),
        title: 'Forgotten Circles',
        price: 39900,
      },
    ],
  },
  {
    urn: GameURN.stringify('azul'),
    title: 'Azul',
    mechanisms: ['tile placement', 'pattern building'],
    players: '2-4',
    playtime: '30-45 min',
    complexity: 1.8,
    price: 34900,
    availability: 'in-stock',
    expansions: [],
  },
  {
    urn: GameURN.stringify('viticulture'),
    title: 'Viticulture Essential Edition',
    mechanisms: ['worker placement', 'economic'],
    players: '1-6',
    playtime: '45-90 min',
    complexity: 2.9,
    price: 64900,
    availability: 'in-stock',
    expansions: [
      {
        urn: ExpansionURN.forGame('viticulture', 'tuscany'),
        title: 'Tuscany Essential Edition',
        price: 44900,
      },
    ],
  },
  {
    urn: GameURN.stringify('dominion'),
    title: 'Dominion',
    mechanisms: ['deckbuilder', 'engine building'],
    players: '2-4',
    playtime: '30 min',
    complexity: 2.4,
    price: 44900,
    availability: 'in-stock',
    expansions: [
      {
        urn: ExpansionURN.forGame('dominion', 'intrigue'),
        title: 'Intrigue',
        price: 39900,
      },
      {
        urn: ExpansionURN.forGame('dominion', 'seaside'),
        title: 'Seaside',
        price: 39900,
      },
    ],
  },
  {
    urn: GameURN.stringify('root'),
    title: 'Root',
    mechanisms: ['area control', 'asymmetric powers'],
    players: '2-4',
    playtime: '60-90 min',
    complexity: 3.8,
    price: 69900,
    availability: 'preorder',
    expansions: [
      {
        urn: ExpansionURN.forGame('root', 'riverfolk'),
        title: 'The Riverfolk Expansion',
        price: 34900,
      },
    ],
  },
  {
    urn: GameURN.stringify('ark-nova'),
    title: 'Ark Nova',
    mechanisms: ['engine building', 'tile placement'],
    players: '1-4',
    playtime: '90-150 min',
    complexity: 3.8,
    price: 79900,
    availability: 'reprint-pending',
    expansions: [],
  },
  {
    urn: GameURN.stringify('flamme-rouge'),
    title: 'Flamme Rouge',
    mechanisms: ['deckbuilder', 'racing'],
    players: '2-4',
    playtime: '30-45 min',
    complexity: 1.7,
    price: 39900,
    availability: 'in-stock',
    expansions: [],
  },
  {
    urn: GameURN.stringify('crokinole'),
    title: 'Crokinole',
    mechanisms: ['dexterity'],
    players: '2-4',
    playtime: '15-30 min',
    complexity: 1.1,
    price: 119900,
    availability: 'in-stock',
    expansions: [],
  },
  {
    urn: GameURN.stringify('spirit-island'),
    title: 'Spirit Island',
    mechanisms: ['co-op', 'area control'],
    players: '1-4',
    playtime: '90-120 min',
    complexity: 4.0,
    price: 84900,
    availability: 'in-stock',
    expansions: [
      {
        urn: ExpansionURN.forGame('spirit-island', 'jagged-earth'),
        title: 'Jagged Earth',
        price: 89900,
      },
    ],
  },
  {
    urn: GameURN.stringify('agricola'),
    title: 'Agricola',
    mechanisms: ['worker placement', 'farming'],
    players: '1-4',
    playtime: '60-120 min',
    complexity: 3.6,
    price: 59900,
    availability: 'out-of-print',
    expansions: [],
  },
] as const;
